# Add source files here
EXECUTABLE	:= FloorplannerEA
# Cuda source files (compiled with cudacc)
CUFILES		:= \
	computeWireTemp.cu
# CUDA dependency files
CU_DEPS		:= \
	computeWireTemp_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \
	ComponentVariable.cpp Solutions.cpp Floorplanner.cpp Markup.cpp FloorplanConfiguration.cpp


################################################################################
# Rules and targets

include ../../common/common.mk
